=== M-Igashi/cologne-raves/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "venue",
      "date",
      "title",
      "startTime"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "venue": {
        "type": "string"
      },
      "date": {
        "type": "string",
        "format": "date"
      },
      "title": {
        "type": "string"
      },
      "startTime": {
        "type": "string",
        "pattern": "^\\d{2}:\\d{2}$"
      },
      "artists": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "url": {
        "type": "string",
        "format": "uri"
      }
    },
    "additionalProperties": false
  }
}

=== M-Igashi/cologne-raves/data/formatted-may2025-events-deduped.json
[
  {
    "id": "",
    "title": "Ascension with MASSAGIO, Critical Error, AVO2X, Dopair, Dana Roosy",
    "venue": "Helios37",
    "date": "2025-05-02",
    "startTime": "23:00",
    "artists": [
      "MASSAGIO",
      "AVO2X",
      "Bensonius",
      "Dana Roosy"
    ],
    "url": "https://ra.co/events/2150428"
  },
  {
    "id": "",
    "title": "Fejka",
    "venue": "Yuca Club",
    "date": "2025-05-02",
    "startTime": "19:00",
    "artists": [
      "Fejká"
    ],
    "url": "https://ra.co/events/2105644"
  },
  {
    "id": "",
    "title": "Intertrax with Radial Gaze & Etane",
    "venue": "Zum Scheuen Reh",
    "date": "2025-05-02",
    "startTime": "22:00",
    "artists": [
      "Radial Gaze",
      "Etane"
    ],
    "url": "https://ra.co/events/2150171"
  },
  {
    "id": "",
    "title": "CLUBNACHT - Free Entry",
    "venue": "Nachtigall",
    "date": "2025-05-02",
    "startTime": "23:00",
    "artists": [
      "Pardis"
    ],
    "url": "https://ra.co/events/2144847"
  },
  {
    "id": "",
    "title": "EhrenKlub in Odonien #20 mit Franky-B, Isabelle Beaucamp, SANTØS uvm",
    "venue": "Odonien",
    "date": "2025-05-03",
    "startTime": "23:00",
    "artists": [
      "ALLY",
      "Dana Roosy",
      "Franky-B",
      "Isabelle Beaucamp",
      "Tzaar",
      "DOCTOR MÜCKE"
    ],
    "url": "https://ra.co/events/2147734"
  },
  {
    "id": "",
    "title": "giegling in Köln",
    "venue": "fi",
    "date": "2025-05-03",
    "startTime": "23:00",
    "artists": [
      "Leafar Legov",
      "Edward",
      "Cosmo (KR)",
      "Konstantin",
      "Yamour",
      "UNOS"
    ],
    "url": "https://ra.co/events/2126262"
  },
  {
    "id": "",
    "title": "BergWacht Ladies Night w/ SUZé, Elotanz, Klarabell, JuNi",
    "venue": "Artheater",
    "date": "2025-05-03",
    "startTime": "23:00",
    "artists": [
      "SUZé"
    ],
    "url": "https://ra.co/events/2163398"
  },
  {
    "id": "",
    "title": "Hardfusion - Cyber Meltdown",
    "venue": "Domhof",
    "date": "2025-05-03",
    "startTime": "22:00",
    "artists": [],
    "url": "https://ra.co/events/2143283"
  },
  {
    "id": "",
    "title": "SECRETRAVES // BIG SUMMER OPENING // OPEN AIR",
    "venue": "TBA - SECRET OPEN AIR",
    "date": "2025-05-03",
    "startTime": "19:00",
    "artists": [],
    "url": "https://ra.co/events/2162671"
  }
]

=== M-Igashi/cologne-raves/data/2026-09-kinkycircus-events.json
[
  {
    "title": "Kinky Circus",
    "venue": "Club Bahnhof Ehrenfeld",
    "date": "2026-09-26",
    "startTime": "22:00",
    "artists": [
      "Adahsoe",
      "La Vache",
      "Finyx",
      "Maleeha",
      "Ellavic",
      "Spelta"
    ],
    "url": "https://www.kinkycircus.de/tickets/koeln-26-09-2026-standard-ticket/"
  }
]

=== M-Igashi/cologne-raves/data/2026-07-fi-events.json
[
  {
    "title": "fi x DJ Mell G & Neue Wellen",
    "venue": "fi",
    "date": "2026-07-04",
    "startTime": "23:00",
    "artists": [
      "DJ MELL G",
      "2N1A",
      "SAVSANNAH",
      "FINE DINING",
      "VLIZZ",
      "YUNES"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-dj-mell-g-neue-wellen-0/",
    "id": "c5945f83"
  },
  {
    "title": "fi x Mama Snake & Loveselectors",
    "venue": "fi",
    "date": "2026-07-18",
    "startTime": "23:00",
    "artists": [
      "HENSO",
      "MAMA SNAKE",
      "NO:ELIA",
      "DJ KNUCKLE-BARRY",
      "JOHN WEGEHAUPT",
      "KOGI",
      "LIZZLE",
      "RAFIKI",
      "SNEAKY PETE",
      "ZINHO"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-mama-snake-loveselectors-0/",
    "id": "74332509"
  },
  {
    "title": "fi x NUOBN x Iptamenos Discos x Local Suicide",
    "venue": "fi",
    "date": "2026-07-24",
    "startTime": "23:00",
    "artists": [
      "ETANE",
      "LOCAL SUICIDE",
      "VIOLENCE MARY"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-nuobn-x-local-suicide-0/",
    "id": "5b8b038f"
  },
  {
    "title": "fi Garten x Langer Tag x Roman Flügel & Jonathan Kaspar & Barulho World uvm",
    "venue": "fi",
    "date": "2026-07-25",
    "startTime": "14:00",
    "artists": [
      "Roman Flügel",
      "Jonathan Kaspar",
      "Barulho World",
      "FrauBeji",
      "Piccell",
      "Frisotto",
      "Noah Boehm",
      "Henning Pott",
      "Yonah",
      "Kobi Föhres",
      "Arthur Uhing",
      "Lara G.",
      "Thalheimer"
    ],
    "url": "https://www.eventbrite.de/e/fi-garten-x-langer-tag-x-roman-flugel-jonathan-kaspar-barulho-world-uvm-tickets-1992487592024",
    "id": "b2a26b75"
  }
]

=== M-Igashi/cologne-raves/data/2025-07-cologne-16-to-08-02.json
[
  {
    "id": "7550b070",
    "title": "Beats x Bass x Cologne w/ Sofie Sapuna #MittWochenende",
    "venue": "Odonien",
    "date": "2025-07-16",
    "startTime": "23:00",
    "artists": [
      "Sofie Sapuna",
      "Rosilicious",
      "LSG",
      "DJ Discostoff",
      "Gourski",
      "Enaly"
    ],
    "url": "https://ra.co/events/2208948"
  },
  {
    "id": "b199d3ac",
    "title": "Andhim in Odonien",
    "venue": "Odonien",
    "date": "2025-07-18",
    "startTime": "23:00",
    "artists": [
      "Andhim",
      "Rafael Da Cruz",
      "Julian Bomm",
      "Mike Momburg"
    ],
    "url": "https://ra.co/events/2189227"
  },
  {
    "id": "a2f94344",
    "title": "THICK & JUICY - KHM Rundgangsparty 2025",
    "venue": "JAKI",
    "date": "2025-07-18",
    "startTime": "23:00",
    "artists": [
      "Sedaction",
      "low Ki"
    ],
    "url": "https://ra.co/events/2211896"
  },
  {
    "id": "83c78b0a",
    "title": "Technoblock Hardtechno x Hardbounce Session",
    "venue": "Elektroküche",
    "date": "2025-07-19",
    "startTime": "23:00",
    "artists": [
      "FØSS",
      "Boltcore",
      "Faronis"
    ],
    "url": "https://ra.co/events/2202913"
  },
  {
    "id": "2b069946",
    "title": "BergWacht in Odonien with Miss Melera, Lampé uvm",
    "venue": "Odonien",
    "date": "2025-07-19",
    "startTime": "23:00",
    "artists": [
      "Miss Melera",
      "Lampé",
      "Liho"
    ],
    "url": "https://ra.co/events/2199370"
  },
  {
    "id": "322a3757",
    "title": "inner rhythm",
    "venue": "Tanzfaktur",
    "date": "2025-07-19",
    "startTime": "14:00",
    "artists": [
      "Nadim",
      "HiHat",
      "DJ Palga"
    ],
    "url": "https://ra.co/events/2196488"
  },
  {
    "id": "a1670f67",
    "title": "Tom-Tom Club feat. DJ Lu & Nadim",
    "venue": "JAKI",
    "date": "2025-07-19",
    "startTime": "23:30",
    "artists": [
      "Nadim"
    ],
    "url": "https://ra.co/events/2200041"
  },
  {
    "id": "28f77686",
    "title": "VICE BOAT CRUISE 2025 with Leon Hagen & Pascal Wagner (HOOVE)",
    "venue": "TBA - Anleger 13 - Bastei Köln (MS Rheinland)",
    "date": "2025-07-19",
    "startTime": "16:30",
    "artists": [
      "Leon Hagen",
      "Pascal Wagner"
    ],
    "url": "https://ra.co/events/2210643"
  },
  {
    "id": "bd6589b3",
    "title": "fi x Lange Nacht",
    "venue": "fi",
    "date": "2025-07-19",
    "startTime": "18:00",
    "artists": [
      "Philipp Stoffel",
      "Mike Momburg",
      "Leon Hagen",
      "Pascal Wagner"
    ],
    "url": "https://ra.co/events/2209647"
  },
  {
    "id": "6bc56a82",
    "title": "FLINTA* DJ CONTEST - GIRLS JUST WANNA HAVE FUN'",
    "venue": "H26",
    "date": "2025-07-19",
    "startTime": "22:00",
    "artists": [
      "AGNY"
    ],
    "url": "https://ra.co/events/2212560"
  },
  {
    "id": "7f6d49e0",
    "title": "Beats x Bass x Cologne #MittWochenende",
    "venue": "Odonien",
    "date": "2025-07-23",
    "startTime": "23:00",
    "artists": [],
    "url": "https://ra.co/events/2208992"
  },
  {
    "id": "f98eb2d8",
    "title": "Sommer Rave at Odonien",
    "venue": "Odonien",
    "date": "2025-07-25",
    "startTime": "23:00",
    "artists": [
      "Ankytrixx",
      "Alchemiah",
      "Kos:mo",
      "Shaun Moses",
      "Steven Shade",
      "Laura Foxx"
    ],
    "url": "https://ra.co/events/2170037"
  },
  {
    "id": "ff7f1ab5",
    "title": "Austin Millz pres by Bootshaus LIVE",
    "venue": "Bootshaus",
    "date": "2025-07-25",
    "startTime": "19:00",
    "artists": [
      "Austin Millz"
    ],
    "url": "https://ra.co/events/2195675"
  },
  {
    "id": "146ab00a",
    "title": "FOR FREE - Artheater SUMMER SPECIAL I",
    "venue": "Artheater",
    "date": "2025-07-25",
    "startTime": "23:00",
    "artists": [
      "Redfocks",
      "DJ VENUSSS"
    ],
    "url": "https://ra.co/events/2212653"
  },
  {
    "id": "70987d70",
    "title": "fi = altshift5 with Marcel Dettmann & Plasma & rau.ton",
    "venue": "fi",
    "date": "2025-07-26",
    "startTime": "23:00",
    "artists": [
      "Elisen",
      "Marcel Dettmann",
      "BORGBORG",
      "makahaun",
      "Rostøm"
    ],
    "url": "https://ra.co/events/2209588"
  },
  {
    "id": "e938f2bd",
    "title": "BZZBZZ TECHNO X RCL w/Raven",
    "venue": "Helios37",
    "date": "2025-07-26",
    "startTime": "23:00",
    "artists": [
      "Raven (CA)",
      "SPEEDO (2)",
      "KACHU2K"
    ],
    "url": "https://ra.co/events/2208076"
  },
  {
    "id": "56e2896f",
    "title": "In Limbo Audio Open Air",
    "venue": "Autonomes Zentrum",
    "date": "2025-07-26",
    "startTime": "14:00",
    "artists": [
      "AMSL",
      "Motip White",
      "Separat"
    ],
    "url": "https://ra.co/events/2211137"
  },
  {
    "id": "249426a5",
    "title": "DJ DIESEL pres. by SHAQ´S BASS ALL-STARS",
    "venue": "Bootshaus",
    "date": "2025-07-26",
    "startTime": "22:00",
    "artists": [
      "San Holo"
    ],
    "url": "https://ra.co/events/2186555"
  },
  {
    "id": "987531b4",
    "title": "HNTR PRES BY Bootshaus",
    "venue": "Bootshaus",
    "date": "2025-07-26",
    "startTime": "23:00",
    "artists": [
      "HNTR",
      "Nic Lorenz"
    ],
    "url": "https://ra.co/events/2171583"
  },
  {
    "id": "ff9d3cb2",
    "title": "Tom-Tom Club x Diana Kollektiv x Another Thought",
    "venue": "JAKI",
    "date": "2025-07-26",
    "startTime": "23:30",
    "artists": [],
    "url": "https://ra.co/events/2196577"
  },
  {
    "id": "dc791c97",
    "title": "AMAPIANO FEST - OPEN AIR EDITION",
    "venue": "TBA - MOXY COLOGNE/BONN AIRPORT",
    "date": "2025-07-27",
    "startTime": "16:00",
    "artists": [
      "DJ Freegah",
      "Cajoux"
    ],
    "url": "https://ra.co/events/2201230"
  },
  {
    "id": "be0a9510",
    "title": "Bootshaus on a Ship with Muzz, Subsonic, Aeon:Mode",
    "venue": "TBA",
    "date": "2025-07-27",
    "startTime": "14:00",
    "artists": [
      "Gourski"
    ],
    "url": "https://ra.co/events/2185978"
  },
  {
    "id": "13789217",
    "title": "Beats x Bass x Cologne #MittWochenende",
    "venue": "Odonien",
    "date": "2025-07-30",
    "startTime": "23:00",
    "artists": [],
    "url": "https://ra.co/events/2208994"
  },
  {
    "id": "d2ece4e7",
    "title": "ART OF URBAN LIFE SPECIAL - BIRTHDAY RAVE",
    "venue": "Artheater",
    "date": "2025-08-01",
    "startTime": "23:00",
    "artists": [
      "CÖLN",
      "SITTENLOS",
      "DJ SODBRENNEN"
    ],
    "url": "https://ra.co/events/2208485"
  },
  {
    "id": "0c0f0d7e",
    "title": "Techno Allianz Pres. 1 Year Schranz Only Local Night",
    "venue": "Elektroküche",
    "date": "2025-08-02",
    "startTime": "23:00",
    "artists": [
      "Ropemaker",
      "Roben Gardemann",
      "I.D.A"
    ],
    "url": "https://ra.co/events/2169254"
  },
  {
    "id": "2ac2dd1d",
    "title": "Techno Dampfer Köln with Spartaque",
    "venue": "TBA - Am Leystapel auf der Höhe des Schokoladenmuseums, Köln",
    "date": "2025-08-02",
    "startTime": "17:00",
    "artists": [
      "Spartaque"
    ],
    "url": "https://ra.co/events/2121363"
  },
  {
    "id": "95eabbc2",
    "title": "GUTE NACHT! mit Chrissyjeey und sarah4K im Helios37",
    "venue": "Helios37",
    "date": "2025-08-02",
    "startTime": "23:00",
    "artists": [
      "Bounce MC",
      "sarah4K",
      "Speedo"
    ],
    "url": "https://ra.co/events/2207876"
  },
  {
    "id": "4c7689a4",
    "title": "FOR FREE - Artheater SUMMER SPECIAL II",
    "venue": "Artheater",
    "date": "2025-08-02",
    "startTime": "23:00",
    "artists": [
      "alleira",
      "Arninho",
      "BOLZ"
    ],
    "url": "https://ra.co/events/2212656"
  }
]

=== M-Igashi/cologne-raves/data/2025-09-cologne-30-b74ccf.json
[
  {
    "id": "1d50f8b8",
    "title": "MITTWOCHENENDE feat. RAVES of GERMANY & MK RAVES",
    "venue": "Odonien",
    "date": "2025-10-01",
    "startTime": "23:00",
    "artists": [
      "Simba",
      "Super Dario",
      "Dj Danevska",
      "Dj Eddyble",
      "Dj MÃ¤sisch B2B ISSAM",
      "Dr Pheelgood",
      "Rui Da Silva",
      "Bbxngz",
      "Prayinhell",
      "Zoltec"
    ],
    "url": "https://tonite.ticket.io/8D6vdzsF/"
  }
]

=== M-Igashi/cologne-raves/data/2026-08-odonien-events.json
[
  {
    "title": "WIR Schwestern ･ New Frequencies",
    "venue": "Odonien",
    "date": "2026-08-01",
    "startTime": "23:00",
    "artists": [
      "LOLSNAKE",
      "ESZTER",
      "REDFOCKS",
      "CALI CARACHO",
      "RACHEL RAW",
      "ROMY MVP",
      "GRETA PEROLA",
      "LEYA",
      "VIBE & VIPER",
      "ENNA"
    ],
    "url": "https://rausgegangen.de/events/wir-schwestern-new-frequencies-august-rush-0/",
    "id": "9dbc2c56"
  },
  {
    "title": "Electronic Summer of Love '26 (Friday)",
    "venue": "Odonien",
    "date": "2026-08-07",
    "startTime": "23:00",
    "artists": [
      "Laura vom Jupiter",
      "LIEKS",
      "Matech",
      "NVNS",
      "Perle",
      "Chaya",
      "Isabelle Beaucamp",
      "IN FURCHT",
      "SUP"
    ],
    "url": "https://rausgegangen.de/events/electronic-summer-of-love-2026-the-odonien-festival-part-xiv-0/",
    "id": "1fc116f4"
  },
  {
    "title": "Electronic Summer of Love '26 (Saturday Day Rave)",
    "venue": "Odonien",
    "date": "2026-08-08",
    "startTime": "14:00",
    "artists": [
      "Danilo Filipe",
      "DJ Sodbrennen",
      "Jacuzi",
      "Limoncello",
      "Lola Cerise",
      "Ben Techy",
      "DJ Danevska",
      "EDNA",
      "Pipo",
      "ROWIN",
      "Bish",
      "Enaly",
      "Gourski",
      "LAETi",
      "Natty Lou",
      "Omox"
    ],
    "url": "https://rausgegangen.de/events/electronic-summer-of-love-2026-the-odonien-festival-part-xiv-0/",
    "id": "07dccb6f"
  },
  {
    "title": "SUMMER RAVE in ODONIEN by ART OF URBAN LIFE & ONLYRAVES",
    "venue": "Odonien",
    "date": "2026-08-22",
    "startTime": "23:00",
    "artists": [],
    "url": "https://tonite.ticket.io/dIQ2mcZp/",
    "id": "c0867e39"
  }
]

=== M-Igashi/cologne-raves/data/2026-11-odonien-events.json
[
  {
    "title": "Alaaf mit saus & braus / Rheinfeuern",
    "venue": "Odonien",
    "date": "2026-11-11",
    "startTime": "14:00",
    "artists": [
      "Oliver Koletzki",
      "Adriano Rosso b2b Jeremy Reinhard",
      "Fabian Sprungk",
      "Henning Pott",
      "Lukas Thalheimer",
      "Janelie",
      "Lilah",
      "Nick Lase"
    ],
    "url": "https://www.eventbrite.de/e/1111-in-odonien-18h-outdoorindoor-rave-i-oliver-koletzki-uvm-tickets-2000522654111",
    "id": "3dafb861"
  }
]

=== M-Igashi/cologne-raves/data/2026-07-gewoelbe-events.json
[
  {
    "title": "Phonovision CSD",
    "venue": "Gewölbe",
    "date": "2026-07-04",
    "startTime": "23:00",
    "artists": [
      "Alleira & Skathi",
      "DJ Ass Tits & Various Identities",
      "DJ Fucks Himself & HiHat"
    ],
    "url": "https://gewoelbe.ticket.io/4C4Mq92X/",
    "id": "c2fb3604"
  },
  {
    "title": "Jack This",
    "venue": "Gewölbe",
    "date": "2026-07-11",
    "startTime": "23:00",
    "artists": [
      "Clara Luise",
      "Pancratio",
      "Måtyrer"
    ],
    "url": "https://gewoelbe.ticket.io/MWK2ya3V/",
    "id": "28967670"
  },
  {
    "title": "Gewölbe @Odonien",
    "venue": "Odonien",
    "date": "2026-07-31",
    "startTime": "23:00",
    "artists": [],
    "url": "https://gewoelbe.ticket.io/7CWbGZ6s/",
    "id": "7330a795"
  }
]
