=== M-Igashi/cologne-raves/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "venue",
      "date",
      "title",
      "startTime"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "venue": {
        "type": "string"
      },
      "date": {
        "type": "string",
        "format": "date"
      },
      "title": {
        "type": "string"
      },
      "startTime": {
        "type": "string",
        "pattern": "^\\d{2}:\\d{2}$"
      },
      "artists": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "url": {
        "type": "string",
        "format": "uri"
      }
    },
    "additionalProperties": false
  }
}

=== M-Igashi/cologne-raves/data/2025-12-cologne-05-658735.json
[
  {
    "id": "0b99aad3",
    "title": "PSYCHO THRILL :: 34 Years of Science Friction Techno",
    "venue": "somewhere in Cologne :D",
    "date": "2025-12-06",
    "startTime": "22:00",
    "artists": [
      "ALEC TUCKER",
      "CLAUS BACHOR",
      "DJ ALTO",
      "DRIVETRAIN",
      "DRUM:MAJOR 2525",
      "MaeshRoombOY UA",
      "MARKUS FUNKE",
      "REDMADVELVET",
      "ROLAND CASPER"
    ],
    "url": "https://www.facebook.com/events/1314256426644061/"
  }
]

=== M-Igashi/cologne-raves/data/2025-10-cologne-01-2fcf86.json
[
  {
    "id": "cbf8771b",
    "title": "High Voltage X KÃ¶ln ist Techno - prod. by MATTERMIND",
    "venue": "BOGEN 2",
    "date": "2025-10-02",
    "startTime": "23:00",
    "artists": [
      "@ambam.69",
      "@bbxngz",
      "@dana.roosy",
      "@jowijane",
      "@sofiesapuna_music"
    ],
    "url": "https://www.mattermindevents.de/highvoltage"
  }
]

=== M-Igashi/cologne-raves/data/2026-10-fi-events.json
[
  {
    "title": "fi x Patrick Mason & Loveselectors",
    "venue": "fi",
    "date": "2026-10-03",
    "startTime": "23:00",
    "artists": [
      "Patrick Mason",
      "Eva Mo",
      "Juni",
      "DJ Ass Tits",
      "Juno",
      "Rafiki b2b Zinho"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-patrick-mason-loveselectors-0/",
    "id": "f3a88ec0"
  },
  {
    "title": "fi x Lammer & Wetdreams & SoundSound",
    "venue": "fi",
    "date": "2026-10-09",
    "startTime": "23:00",
    "artists": [
      "Lammer",
      "Mismatch b2b M4X",
      "Bædura b2b Lizzle",
      "909 Racing Team b2b Vagabund",
      "Carl Bergé",
      "Skathi b2b Alleira"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-lammer-wetdreams-soundsound-0/",
    "id": "36b1d615"
  },
  {
    "title": "fi x Rene Wise & Das Ist Das Ja",
    "venue": "fi",
    "date": "2026-10-10",
    "startTime": "23:00",
    "artists": [
      "Rene Wise",
      "Mariami",
      "Medea",
      "0megavybe",
      "Anatoli b2b Dennis Janeczek",
      "Jan Oben"
    ],
    "url": "https://ursprung-fi.de/",
    "id": "24bc4db3"
  },
  {
    "title": "fi x The Hacker & Hoove",
    "venue": "fi",
    "date": "2026-10-16",
    "startTime": "23:00",
    "artists": [
      "The Hacker",
      "Alfalfa b2b Julian Bomm",
      "Krackk",
      "Greta Perola",
      "Leon Hagen",
      "Thalo Santana"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-the-hacker-hoove-0/",
    "id": "6ad5e944"
  },
  {
    "title": "fi x Kollektiv Turmstrasse & Jonathan Kaspar & friendly Connections",
    "venue": "fi",
    "date": "2026-10-17",
    "startTime": "23:00",
    "artists": [
      "Kollektiv Turmstrasse (live)",
      "Jonathan Kaspar",
      "Herkules Underground",
      "We Love Warmups",
      "Zweite Sahne"
    ],
    "url": "https://www.eventbrite.de/e/fi-x-kollektiv-turmstrasse-jonathan-kaspar-friendly-connections-tickets-1998414548711",
    "id": "109f3c09"
  },
  {
    "title": "fi x Henrik Schwarz & AYA",
    "venue": "fi",
    "date": "2026-10-23",
    "startTime": "23:00",
    "artists": [
      "Henrik Schwarz (live)",
      "Bamina b2b Efuru",
      "Bonjour Ben",
      "c00lm8",
      "Neeks b2b Monsi"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-henrik-schwarz-aya-0/",
    "id": "36702a0f"
  },
  {
    "title": "fi x Brutalism x Waidmarkt",
    "venue": "fi",
    "date": "2026-10-24",
    "startTime": "23:00",
    "artists": [
      "Cio D'Or",
      "Dornen",
      "Function",
      "lomi",
      "Grim",
      "Kgavasheli",
      "Philip Morris"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-brutalism-x-waidmarkt-0/",
    "id": "ef47c294"
  },
  {
    "title": "fi x Kittin & Lafari",
    "venue": "fi",
    "date": "2026-10-31",
    "startTime": "23:00",
    "artists": [
      "Kittin",
      "Etane",
      "Pileta",
      "Daddy Dee",
      "Rufous",
      "Steve Bonde",
      "Uwe Lacto",
      "Zahara"
    ],
    "url": "https://rausgegangen.de/en/events/fi-x-kittin-lafari-0/",
    "id": "4d8e3c09"
  }
]

=== M-Igashi/cologne-raves/data/2025-04-cologne-08-extract-2.json
[

  {
    "id": "3ca0a252",
    "venue": "Bootshaus",
    "date": "2025-05-23",
    "title": "CHROME COLOGNE W. JAZZY, OMAKS, SECRET GUEST & MORE",
    "artists": [
      "JAZZY (2)",
      "OMAKS",
      "HOEHENANGST",
      "Leonard Palm",
      "Tzaar"],
    "startTime": "23:00",
    "url": "https://bootshaus-club.ticket.io/0mckscju/?fbclid=PAZXh0bgNhZW0CMTEAAachtSEwbiVUVh3obv4o3GHh8DRx7a4JoIZYB1fjm9JIU-k5Ju8WVC9QUBBETw_aem_Fh1s1TXt239nbwpvHgMqCw"
  },

  { "venue": "Helios 37",
    "date": "2025-04-26",
    "title": "NURBÖSE – 26.04.2025 – Tag der Lesbischen Sichtbarkeit",
    "artists": [
      "Métaraph",
      "Døpair",
      "Nina Sativa",
      "Sadicca"
    ],
    "startTime": "23:00",
    "url": "https://t.rausgegangen.de/tickets/nurbose-26042025"
  },
  { "venue": "Helios 37",
    "date": "2025-05-24",
    "title": "NURBÖSE – 26.04.2025 – Tag der Lesbischen Sichtbarkeit",
    "artists": [
      "Métaraph",
      "Døpair",
      "Nina Sativa",
      "Sadicca"
    ],
    "startTime": "23:00",
    "url": "https://t.rausgegangen.de/tickets/nurbose-26042025"
  },

  { "venue": "Club Zimmermanns",
    "date": "2025-05-17",
    "title": "Kinky Techno & Friends ",
    "artists": ["Moekli",
      "Hill",
      "Gerrit X",
      "Deniz (LJ)"],
    "startTime": "22:00",
    "url": "https://www.instagram.com/p/DGDR6fANkiA/"
  }
]

=== M-Igashi/cologne-raves/data/2026-nurboese-events.json
[
  {
    "venue": "Garagen Club",
    "date": "2026-08-28",
    "title": "CHIN CHIN im Zauberwald",
    "startTime": "20:00",
    "artists": [
      "Lilah",
      "Nico Held B2B Lou.Key",
      "ENNA B2B Vinni",
      "Finyx",
      "Erasmus wie Orgasmus ",
      "Luzia",
      "MARRED",
      "Maxim"
    ],
    "url": "https://ausgehfuchs-dpcy.vivenushop.com/event/chin-chin-im-zauberwald-dqhf7n?utm_campaign=W7oU23MY&utm_source=shareable_link",
    "id": "6f82d003"
  },
  {
    "venue": "Garagen Club",
    "date": "2026-03-21",
    "title": "NURFLUID Köln",
    "startTime": "23:00",
    "artists": [
      "Nur Jaber",
      "Nana Yaa",
      "Heepmann",
      "Døpair",
      "Bouncy Bitch",
      "Selunia",
      "B!B!",
      "Zuza"
    ],
    "url": "https://nurboese.de/events/nurfluid-koeln-21-03-2026/",
    "id": "bdab9d39"
  },
  {
    "venue": "Helios37",
    "date": "2026-04-18",
    "title": "NURBÖSE Köln",
    "startTime": "23:00",
    "artists": [
      "MÉTARAPH",
      "ARES",
      "DØPAIR",
      "SØSSA"
    ],
    "url": "https://rausgegangen.de/en/events/nurbose-1804-0/?mtm_campaign=teilen_gewinnspiel&mtm_kwd=web",
    "id": "1aa040e2"
  },
  {
    "venue": "Helios37",
    "date": "2026-05-16",
    "title": "NURBÖSE Köln",
    "startTime": "23:00",
    "artists": [
      "Neon Graveyard",
      "DØPAIR",
      "Esther",
      "Sadicca b2b Maddycation"
    ],
    "url": "https://rausgegangen.de/en/events/nurbose-1605-0/?action=participate-lottery-nurbose-1605-0?mtm_campaign=teilen_gewinnspiel&mtm_kwd=web",
    "id": "9cd25a16"
  },
  {
    "venue": "Artheater",
    "date": "2026-06-13",
    "title": "NURFLUID Köln",
    "startTime": "23:00",
    "artists": [
      "Bouncy Bitch",
      "Falk",
      "Leo Pardy",
      "Szunflower",
      "Mami Wata",
      "Cristian Martinez"
    ],
    "url": "https://nurboese.de/events/nurfluid-13-06/",
    "id": "af74310e"
  },
  {
    "venue": "Garagen Club",
    "date": "2026-07-04",
    "title": "NURBÖSE Open Air",
    "startTime": "13:00",
    "artists": [],
    "url": "https://rausgegangen.de/en/events/nurbose-472026-open-air-0/",
    "id": "63f239fd"
  },
  {
    "venue": "Helios37",
    "date": "2026-08-15",
    "title": "NURBÖSE 15.08",
    "startTime": "23:00",
    "artists": [
      "Dannae",
      "Skippo",
      "Crlz",
      "Calima"
    ],
    "url": "https://rausgegangen.de/en/events/nurbose-1508-0/?mtm_campaign=teilen_gewinnspiel&mtm_kwd=web",
    "id": "1de75608"
  },
  {
    "venue": "Helios37",
    "date": "2026-09-19",
    "title": "NURBÖSE 19.09",
    "startTime": "23:00",
    "artists": [
      "Métaraph",
      "Tariel",
      "Cöln",
      "Deysie"
    ],
    "url": "https://rausgegangen.de/en/events/nurbose-1508-1/"
  }
]

=== M-Igashi/cologne-raves/data/2026-02-23-new-ra-events.json
[
  {
    "id": "12e17e2b",
    "venue": "Garagen",
    "date": "2026-02-25",
    "title": "TECHNOLiEBE #AmMittwoch",
    "artists": [],
    "startTime": "20:00",
    "url": "https://ra.co/events/2376939"
  },
  {
    "id": "295360ea",
    "venue": "Elektroküche",
    "date": "2026-02-28",
    "title": "Schranz Only w/TEKKERKANE",
    "artists": [
      "I.D.A"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2342784"
  },
  {
    "id": "4cd8ab3f",
    "venue": "Schrotty",
    "date": "2026-02-28",
    "title": "VOOV PARTY OMIKI-PHAXE-SENSIFEEL",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2374431"
  },
  {
    "id": "12af7a86",
    "venue": "Odonien",
    "date": "2026-03-06",
    "title": "Lichtblick- Season opening 2026 in Odonien",
    "artists": [
      "Alchemiah",
      "Brtinzz",
      "Gilles Bock",
      "Kos:mo"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2321747"
  },
  {
    "id": "06c049ed",
    "venue": "Yuca Club",
    "date": "2026-03-06",
    "title": "EERIE X LOCAL BASS  with BUKEZ FINEZT, Roklem, Sebalo & many more",
    "artists": [
      "BUKEZ FINEZT",
      "Roklem",
      "Sebalo"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2369523"
  },
  {
    "id": "4f3b4c95",
    "venue": "Schrotty",
    "date": "2026-03-06",
    "title": "BZZBZZ TECHNO X MILLIAMPERE",
    "artists": [
      "Paralich",
      "DJ HÖRDE",
      "Eurodance2000",
      "SPEEDO (2)",
      "YËDM",
      "Athina",
      "Shemm",
      "Pamela Rave",
      "HENNESY",
      "PANA (Ger)"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2360225"
  },
  {
    "id": "36a238db",
    "venue": "Artheater",
    "date": "2026-03-06",
    "title": "303 presents O.B.I. & Frederic. (All Night Long)",
    "artists": [
      "O.B.I. (DE)",
      "Frederic.",
      "LSG",
      "Lianka"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2330549"
  },
  {
    "id": "b8b831ee",
    "venue": "Garagen",
    "date": "2026-03-06",
    "title": "BEATS x BASS x WEEKENDER hosted by BLOOMCAST",
    "artists": [
      "Rosilicious",
      "Fae Morgana"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2375480"
  },
  {
    "id": "7529e9b5",
    "venue": "fi",
    "date": "2026-03-06",
    "title": "fi = altshift5 with Ellen Allien & Etage147",
    "artists": [
      "Shaleen"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349249"
  },
  {
    "id": "862efe42",
    "venue": "Helios37",
    "date": "2026-03-06",
    "title": "akt Party",
    "artists": [
      "KLARYOKO",
      "alleira"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2361021"
  },
  {
    "id": "29732710",
    "venue": "JAKI",
    "date": "2026-03-06",
    "title": "JAKI presents: All Night Long with Nadim b2b SPECIAL GUEST",
    "artists": [
      "Nadim"
    ],
    "startTime": "23:30",
    "url": "https://ra.co/events/2373078"
  },
  {
    "id": "76c65b1b",
    "venue": "Bootshaus",
    "date": "2026-03-06",
    "title": "LUKE MADNESS ALL NIGHT LONG [360°]",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2361298"
  },
  {
    "id": "cfd76811",
    "venue": "Kunstwerk",
    "date": "2026-03-07",
    "title": "Øhne Bedenken x 969 - Kollektiv Nacht VOL. II",
    "artists": [
      "Kashinski",
      "PATEK!",
      "andré wiese",
      "bashii (2)",
      "Dj Bowlz"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2365892"
  },
  {
    "id": "32e5a74f",
    "venue": "Bootshaus",
    "date": "2026-03-07",
    "title": "9 YEARS NIBIRII pres. VINI VICI / POLTERGST",
    "artists": [
      "Mr.Black (UK)",
      "DELTA LABS",
      "Paranormila",
      "Rui Da Silva",
      "Enaly",
      "Gourski",
      "LYNE"
    ],
    "startTime": "22:00",
    "url": "https://ra.co/events/2344161"
  },
  {
    "id": "995e5e88",
    "venue": "Helios37",
    "date": "2026-03-07",
    "title": "240KM/H pres. International Women's Day Charity",
    "artists": [
      "Riana Holley",
      "TANJA MIJU"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2353469"
  },
  {
    "id": "00c1d33b",
    "venue": "fi",
    "date": "2026-03-07",
    "title": "fi = altshift5 with 3000 Grad & Tiefgang",
    "artists": [
      "Katzengold",
      "Mollono.Bass",
      "nøvae",
      "J.WOCKENFUSS",
      "NORO",
      "ZHTA"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349587"
  },
  {
    "id": "c03c1a14",
    "venue": "Odonien",
    "date": "2026-03-07",
    "title": "Anti Disco with Lars Eidinger (DJ-Set)",
    "artists": [
      "Lars Eidinger"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349148"
  },

  {
    "id": "79abee3d",
    "venue": "Artheater",
    "date": "2026-03-07",
    "title": "jedermensch. with Caniche & Samantha Togni",
    "artists": [
      "Aaro (3)",
      "Caniche",
      "Samantha Togni",
      "EPHIE"
    ],
    "startTime": "23:00",
    "url": "https://ra.co/events/2362506"
  },
  {
    "id": "f5dffa88",
    "venue": "Blue Shell",
    "date": "2026-03-07",
    "title": "Neon Paradise x Cassetter - Syntwave/Cyberpunk Party",
    "artists": [],
    "startTime": "23:00",
    "url": "https://ra.co/events/2349454"
  },
  {
    "id": "feb41668",
    "venue": "Subway",
    "date": "2026-03-07",
    "title": "IMMERNOCH! TANZEN",
    "artists": [],
    "startTime": "17:00",
    "url": "https://ra.co/events/2360953"
  }
]

=== M-Igashi/cologne-raves/data/2026-08-cologne-14-b64eac.json
[
  {
    "id": "f610c909",
    "title": "Space Invadrz Division ",
    "venue": "Lagerhauskai 1a",
    "date": "2026-08-29",
    "startTime": "22:00",
    "artists": [
      "DETUNE",
      "DANIEL ENGLISCH",
      "MUSE III",
      "MONTY",
      "REDMADVELVET"
    ],
    "url": "https://www.instagram.com/space_invadrz_division_s.i.d"
  }
]

=== M-Igashi/cologne-raves/data/2025-09-cologne-21-a5e61b.json
[
  {
    "id": "fe973136",
    "title": "Desire w/Pegassi ",
    "venue": "Schrotty",
    "date": "2025-10-02",
    "startTime": "23:00",
    "artists": [
      "Pegassi",
      "Beau Didier",
      "Kim Swim",
      "Human Safari",
      "Florian Picasso",
      "Gutkind",
      "Tschatsching"
    ],
    "url": "https://desire-world.ticket.io/Rw9gmhNZ/?utm_medium=paid&utm_source=ig&utm_id=6852456735533&utm_content=6852498116133&utm_term=6852456735733&utm_campaign=6852456735533&fbclid=PAb21jcAM9FPVleHRuA2FlbQEwAGFkaWQAAAY7evor_QGnnZxOyWJC_vO9TlcDDQR-bjnffe766tOXaYuKWZXhmm46jyXmOV0fHlqjQhk_aem_iOHf6WVJVuoYI3kxx6f75A"
  },
  {
    "id": "7f6eebb8",
    "title": "United Kinkdom",
    "venue": "Die Halle Tor 2",
    "date": "2025-10-17",
    "startTime": "21:30",
    "artists": [
      "TBD"
    ],
    "url": "https://anny.co/book/united-kinkdom-171025-die-halle-tor-2"
  },
  {
    "id": "5f04f3d5",
    "title": "Chin Chin Walhalla",
    "venue": "Club Bahnhof Ehrenfeld / YUCA",
    "date": "2025-11-29",
    "startTime": "23:00",
    "artists": [
      "Nico Held",
      "B!B!"
    ],
    "url": "https://vivenu.com/event/chin-chin-koln-walhalla-p15qb6"
  },
  {
    "id": "6ce39454",
    "title": "Unicorn Cologne women power night",
    "venue": "Klub Domhof",
    "date": "2025-10-10",
    "startTime": "22:00",
    "artists": [
      "Pardis",
      "Susi & Paula",
      "Rachel Raw",
      "Dilaval"
    ],
    "url": "https://www.holidayevents.net/unicorncologne-wpn"
  }
]
